# SIF2007 | Chapter 3: Introduction to NumPy

Worked examples accompanying the LaTeX manual. Open this notebook in VS Code, select your SIF2007 Python kernel, and run cells in order. Read the manual for equations, assumptions, interpretation and practice questions.

Before editing: predict the output. Before submitting: restart the kernel and run all cells. The spectrum practice data are illustrative, not observations.

In [1]:
from pathlib import Path
Path("data").mkdir(exist_ok=True)
Path("figures").mkdir(exist_ok=True)

## Importing NumPy

In [2]:
import numpy as np

## Mathematical functions

In [3]:
print(np.sqrt(9.0))       # 3.0
print(np.exp(0.0))        # 1.0
print(np.log(np.e))       # approximately 1.0
print(np.sin(np.pi / 2))  # approximately 1.0

3.0
1.0
1.0
1.0


In [4]:
angle_deg = 30.0
angle_rad = np.deg2rad(angle_deg)
print(np.sin(angle_rad))  # approximately 0.5

0.49999999999999994


## Creating sequences: arange and linspace

In [5]:
x = np.arange(10)
print(x)                 # [0 1 2 3 4 5 6 7 8 9]
print(len(x))            # 10

y = np.linspace(0.0, 10.0, 6)
print(y)                 # [0. 2. 4. 6. 8. 10.]

[0 1 2 3 4 5 6 7 8 9]
10
[ 0.  2.  4.  6.  8. 10.]


## One-dimensional arrays

In [6]:
a = np.array([1, 2, 3])
print(a)
print(a + 1)             # [2 3 4]
print(a * 2)             # [2 4 6]
print(a**2)              # [1 4 9]
print(a[0])              # first entry: 1
print(a[-1])             # last entry: 3
print(a[:2])             # [1 2]

[1 2 3]
[2 3 4]
[2 4 6]
[1 4 9]
1
3
[1 2]


In [7]:
my_list = [1, 2, 3]
print(my_list * 2)        # [1, 2, 3, 1, 2, 3]

[1, 2, 3, 1, 2, 3]


## Two-dimensional arrays and matrix addition

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [1, 1]])
print(A + B)
print(A.shape)           # (2, 2)
print(A.size)            # 4 entries in total
print(len(A))            # 2 rows
print(A[0, 1])           # row 0, column 1: 2
print(A[:, 0])           # first column: [1 3]

[[2 3]
 [4 5]]
(2, 2)
4
2
2
[1 3]
